name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shopware_version:
#          - '6.5.4.0' (Migration error: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1901 Function or expression 'variant_listing_config' cannot be used in the CHECK clause of `variant_listing_config)
          - '6.5.4.1'
          - '6.5.5.0'
          - '6.5.5.1'
          - '6.5.5.2'
          - '6.5.6.0'
          - '6.5.6.1'
#          - '6.5.7.0' (Fatal error: Uncaught Error: Class "Shopware\Tests\Integration\Core\Framework\DataAbstractionLayer\Version\CalculatedPriceFieldTestDefinition" not found in /opt/shopware-remote-api-test-runner/vendor/shopware/platform/src/Core/Framework/DependencyInjection/CompilerPass/EntityCompilerPass.php:50)
          - '6.5.7.1'
          - '6.5.7.2'
          - '6.5.7.3'
          - '6.5.7.4'
          - '6.5.8.0'
          - '6.5.8.1'
          - '6.5.8.2'
          - '6.5.8.3'
          - '6.5.8.4'
          - '6.5.8.5'
          - '6.5.8.6'
          - '6.5.8.7'
          - '6.5.8.8'
          - '6.5.8.9'
          - '6.5.8.10'
          - '6.5.8.11'
          - '6.5.8.12'
          - '6.5.8.13'
          - '6.5.8.14'
          - '6.5.8.15'
          - '6.6.0.0'
          - '6.6.0.1'
          - '6.6.0.2'
          - '6.6.0.3'
          - '6.6.1.0'
          - '6.6.1.1'
          - '6.6.1.2'
          - '6.6.2.0'
          - '6.6.3.0'
          - '6.6.3.1'
          - '6.6.4.0'
          - '6.6.4.1'
          - '6.6.5.0'
          - '6.6.5.1'
          - '6.6.6.0'
          - '6.6.6.1'
          - '6.6.7.0'
          - '6.6.7.1'
          - '6.6.8.0'
          - '6.6.8.1'
          - '6.6.8.2'
        locale: ['de-DE', 'en-GB']
        currency: ['EUR']
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: .
          file: ./docker/production/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.shopware_version }}_${{ matrix.locale }}_${{ matrix.currency }}
          build-args: |
            SHOPWARE_VERSION=${{ matrix.shopware_version }}
            LOCALE=${{ matrix.locale }}
            CURRENCY=${{ matrix.currency }}
